version: "3.8"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    container_name: "api-test"
    command: ["go", "test", "-v", "-cover", "-count=1", "./..."]
    env_file: config.env
    environment:
      - TEST_ON_DOCKER=true
    depends_on:
      - db
  db:
    image: postgres:14.2-alpine3.15
    container_name: "db-test"
    env_file: config.env
